GENERAL_DEPENDENCIES=(
  brightnessctl
  cliphist
  playerctl
  wl-clipboard
  xdg-desktop-portal-hyprland
  xdg-user-dirs
  xorg-xwayland
  zathura-pdf-poppler
)

FILE_MANAGEMENT_DEPENDENCIES=(
  gvfs
  gvfs-mtp
  ntfs-3g
  udisks2
)

SECURITY=(
  firewalld
  gnome-keyring
  hyprpolkitagent
)


HYPRLAND_WM=(
  grim
  hyprland
  ly
  noctalia-shell
  slurp
)

APPLICATIONS=(
  discord
  kitty
  mpv
  obs-studio
  obsidian
  pavucontrol
  ristretto
  thorium-browser-bin
  thunar
  zathura
)

SHELL=(
  starship
  zsh
  zsh-autosuggestions
  zsh-syntax-highlighting
)

CLI_TOOLS=(
  bat
  btop
  deno
  eza
  fd
  fzf
  lazygit
  neovim
  npm
  pnpm
  ripgrep
  tmux
  zoxide
)

PROGRAMMING=(
  jdk-openjdk
  lua
  nodejs
  python
  rustup
)

MAIN_LAPTOP=(
  bluetui
  calf
  easyeffects
  envycontrol
)

SECONDARY_LAPTOP=(
  broadcom-wl
  intel-ivsc-firmware
)

FONTS=(
  noto-fonts
  noto-fonts-cjk
  noto-fonts-emoji
  noto-fonts-extra
  ttf-jetbrains-mono-nerd
  ttf-rubik-vf
)

APPEARANCE=(
  bibata-cursor-theme-bin
  mactahoe-gtk-theme
  mactahoe-icon-theme-git
)

SERVICES=(
  gnome-keyring-daemon.service
  ly@tty2.service
  power-profiles-daemon.service
  firewalld.service
)
