GENERAL=(
  amd-ucode
  brightnessctl
  cliphist
  intel-ucode
  playerctl
  power-profiles-daemon
  upower
  wl-clipboard
  xdg-user-dirs
  xdg-utils
  zathura-pdf-poppler
)

NETWORK=(
  ethtool
  iwd
  networkmanager
  openssh
  wireless-regdb
)

PACKAGE_MANAGEMENT=(
  pacman-contrib
  reflector
  yay
)

FILE_MANAGEMENT=(
  gvfs
  gvfs-mtp
  nfs-utils
  ntfs-3g
  udisks2
  unrar
  unzip
  xz
)

SECURITY=(
  firewalld
  gnome-keyring
  hyprpolkitagent
)

HYPRLAND_WM=(
  grim
  hyprland
  ly
  noctalia-shell
  slurp
  xdg-desktop-portal-hyprland
  xdg-desktop-portal-wlr
  xorg-xwayland
)

AUDIO=(
  alsa-firmware
  alsa-plugins
  alsa-utils
  pipewire
  pipewire-alsa
  pipewire-jack
  pipewire-pulse
  rtkit
  sof-firmware
  wireplumber
)

APPLICATIONS=(
  discord
  kitty
  mpv
  obs-studio
  obsidian
  pavucontrol
  ristretto
  thorium-browser-bin
  thunar
  zathura
  zed
)

SHELL=(
  starship
  zsh
  zsh-autosuggestions
  zsh-syntax-highlighting
)

CLI_TOOLS=(
  bat
  btop
  deno
  eza
  fd
  fzf
  git
  lazygit
  neovim
  npm
  pnpm
  ripgrep
  tldr
  tmux
  uv
  wget
  zoxide
)

PROGRAMMING=(
  jdk-openjdk
  lua
  nodejs
  python
  rustup
)

MAIN_LAPTOP=(
  calf
  easyeffects
  envycontrol
)

SECONDARY_LAPTOP=(
  broadcom-wl
  intel-ivsc-firmware
)

FONTS=(
  noto-fonts
  noto-fonts-cjk
  noto-fonts-emoji
  noto-fonts-extra
  ttf-jetbrains-mono-nerd
  ttf-rubik-vf
)

APPEARANCE=(
  bibata-cursor-theme-bin
  mactahoe-gtk-theme
  mactahoe-icon-theme-git
)

SERVICES=(
  gnome-keyring-daemon.service
  ly@tty2.service
  power-profiles-daemon.service
  firewalld.service
)
